name: Code Analysis on PR

on:
  pull_request:
    branches: [ main, master, develop ]

jobs:
  code-analysis:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Detect project file
        id: proj
        shell: pwsh
        run: |
          $p = (Get-ChildItem -Path $env:GITHUB_WORKSPACE -Filter *.csproj -Recurse | Select-Object -First 1).FullName
          if (-not $p) { Write-Error "No .csproj found."; exit 1 }
          Add-Content -Path $env:GITHUB_OUTPUT -Value "path=$p"

      - name: Restore dependencies
        run: dotnet restore "${{ steps.proj.outputs.path }}"

      - name: Build with analysis (fail on non-suppressed warnings)
        id: build
        run: dotnet build "${{ steps.proj.outputs.path }}" --configuration Release --no-restore /warnaserror /p:ContinuousIntegrationBuild=true

      - name: Close PR on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;

            const message = "❌ PR has been automatically closed due to code analysis failure.\n"
                           + "Please fix all build-breaking warnings/errors "
                           + "(anything not suppressed by the project's <NoWarn>) and open a new PR.";

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: message
            });

            await github.rest.pulls.update({
              owner,
              repo,
              pull_number: prNumber,
              state: "closed"
            });