name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request_target:  # 使用 pull_request_target 触发器
    types: [opened, reopened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}  # Checkout the base branch of the PR (target branch)

      - name: Review PR
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: sk-3ff29f9022e5442496d7e8df313d19df
          LANGUAGE: Chinese
          OPENAI_API_ENDPOINT: https://api.deepseek.com/v1
          MODEL: deepseek-chat
          PROMPT: |
            我将提供给你一段github pull request的file diff。请你扮演一位专业的开源社区开发者，帮我进行code review。
            [[代码审核原则]]
            [代码质量]
            1. 该修改是否有必要，是否相比旧代码有改进或添加了新功能？
            2. 是否有逻辑错误或潜在的运行时错误？
            3. 是否有与其他代码部分的兼容性问题，会不会破坏与修改无关的现有逻辑？
            4. 是否有可以优化的代码结构或逻辑，是否有更简洁或更高效的方式来实现相同功能？
            5. 是否有潜在的性能问题？
            [安全性]
            1. 是否有敏感信息泄露的风险（如硬编码的密钥、密码等）？
            2. 是否有可能运行来路不明的外部代码？

            [[结果返回格式]]
            如果发现任何问题或改进建议，请分点详细列出并说明；如果没有问题，请直接输出“LGTM”表示通过。
          top_p: 1
          temperature: 1.0
          max_tokens: 8192
