name: DeepSeek Code Review

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Gather Changed Files
        run: |
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD)
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Prepare Code for Review
        run: |
          CHANGED_FILES=${{ env.CHANGED_FILES }}
          echo "Preparing code for review..."
          for file in $CHANGED_FILES; do
            if [[ $file == *.json ]] || [[ $file == *.png ]]; then
              continue
            fi
            if [ -f "$file" ]; then
              echo "File: $file"
              cat "$file"
            fi
          done > code_changes.txt

      - name: Analyze with DeepSeek
        env:
          DEEPSEEK_API_KEY: ${{ secrets.VANILLA_GPT_KEY }}  # 确保在仓库 Secrets 中设置 DEEPSEEK_API_KEY
        run: |
          PROMPT=$(cat <<EOF
          我将提供给你一段github pull request的file diff。请你扮演一位专业的开源社区开发者，帮我进行code review。
          [[代码审核原则]]
          [代码质量]
          1. 该修改是否有必要，是否相比旧代码有改进或添加了新功能？
          2. 是否有逻辑错误或潜在的运行时错误？
          3. 是否有与其他代码部分的兼容性问题，会不会破坏与修改无关的现有逻辑？
          4. 是否有可以优化的代码结构或逻辑，是否有更简洁或更高效的方式来实现相同功能？
          5. 是否有潜在的性能问题？
          [安全性]
          1. 是否有敏感信息泄露的风险（如硬编码的密钥、密码等）？
          2. 是否有可能运行来路不明的外部代码？

          [[结果返回格式]]
          如果发现任何问题或改进建议，请分点详细列出并说明；如果没有问题，请直接输出“LGTM”表示通过。
          EOF
          )

          cat code_changes.txt | tee -a prompt.txt
          echo "$PROMPT" > prompt.txt
          curl -sS https://api.deepseek.com/v1 \
            -H "Authorization: Bearer $DEEPSEEK_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "default",  # 根据 DeepSeek 的 API 文档调整模型名称
              "messages": [
                { "role": "system", "content": "You are a code reviewer." },
                { "role": "user", "content": "'$(cat prompt.txt)'" }
              ]
            }' > response.json

          cat response.json

      - name: Post Review Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 提取 DeepSeek 的回复并发布到 PR 中
          COMMENT=$(jq -r '.response_field' response.json)  # 根据 API 返回的结构调整
          gh api \
            repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            -f body="$COMMENT"